apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyclecm
  namespace: gs-test
  labels:
    app.kubernetes.io/name: cyclecm
    app.kubernetes.io/instance: cyclecm-test
    app.kubernetes.io/version: $IMAGE_VERSION
    app.kubernetes.io/component: Service
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: cyclecm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cyclecm
        app.kubernetes.io/instance: cyclecm-test
        app.kubernetes.io/version: $IMAGE_VERSION
        app.kubernetes.io/component: Service
    spec:
      containers:
        - name: cyclecm
          image: gs42/cyclecm:latest
          ports:
            - containerPort: 8080
          env:
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: cyclecm
                  key: pg-host
            - name: PG_PORT
              valueFrom:
                configMapKeyRef:
                  name: cyclecm
                  key: pg-port
            - name: PG_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: cyclecm
                  key: pg-dbname
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: cyclecm
                  key: pg-user
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cyclecm
                  key: pg-password
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 60
            timeoutSeconds: 10
