apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: $EXO_CERT_AUTHORITY
      server: $K8S_SERVER
    name: 7095bd11-9d19-4107-8843-d4e173671db1
contexts:
  - context:
      cluster: 7095bd11-9d19-4107-8843-d4e173671db1
      user: kubernetes-admin
    name: 7095bd11-9d19-4107-8843-d4e173671db1
current-context: 7095bd11-9d19-4107-8843-d4e173671db1
kind: Config
preferences: {}
users:
  - name: kubernetes-admin
    user:
      client-certificate-data: $EXO_CLIENT_CERT
      client-key-data: $EXO_CLIENT_KEY
