apiVersion: v1
kind: Service
metadata:
  name: cyclecm
  namespace: gs-test
  labels:
    app.kubernetes.io/name: cyclecm
    app.kubernetes.io/instance: cyclecm-test
    app.kubernetes.io/component: Service
spec:
  selector:
    app.kubernetes.io/name: cyclecm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

