name: Deploy to Exoscale

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.3'
      id: install

    - name: Deploy to Exoscale
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
