name: Deploy to Exoscale

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.3'
      id: install
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Replace kubeconfig placeholders
      run: |
        echo "Secret value: ${{ secrets.EXO_CERT_AUTHORITY }}"
        sed -i "s#\$EXO_CERT_AUTHORITY#${{ secrets.EXO_CERT_AUTHORITY }}#g" kubernetes/kubeconfig.yaml
        sed -i "s#\$K8S_SERVER#${{ vars.K8S_SERVER }}#g" kubernetes/kubeconfig.yaml
        sed -i "s#\$EXO_CLIENT_CERT#${{ secrets.EXO_CLIENT_CERT }}#g" kubernetes/kubeconfig.yaml
        sed -i "s#\$EXO_CLIENT_KEY#${{ secrets.EXO_CLIENT_KEY }}#g" kubernetes/kubeconfig.yaml
        sed -i "s#\$IMAGE_VERSION#0.0.1#g" kubernetes/deployment.yaml

    - name: Configure Kubectl
      run: |
        echo "Configuring kubectl..."
        cat kubernetes/kubeconfig.yaml
        mkdir -p $HOME/.kube
        cp kubernetes/kubeconfig.yaml $HOME/.kube/config
        kubectl config view
      shell: bash

    - name: Deploy to Exoscale
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
        kubectl apply -f kubernetes/configmap.yaml
